# Source code lines that are known to always output declassified data (i.e. encryption functions)
declassified:
  [
    "lib/aes-xmm.c:345",
    "drivers/symcrypt/symcryp+0x1146a",
    "drivers/symcrypt/symcryp+0x11471",
    "drivers/symcrypt/symcryp+0x11479",
    "drivers/symcrypt/symcryp+0x11480",
    "drivers/symcrypt/symcryp+0x11488",
    "drivers/symcrypt/symcryp+0x11490",
    "drivers/symcrypt/symcryp+0x11497",
  ]
# Addresses of known symbols in memory, in the form of <sym_name>: [start_address, size]
# TODO: get these values from the driver somehow
known_syms:
  {
    "pub": [0x8c2ef0, 0x10],
    "pub->data": [0x8c2e00, 0x4a],
    "priv": [0x8c2f10, 0x10],
    "priv->data": [0x8c2e60, 0x20],
  }
# Source code lines that output a key (e.g. key expansion)
key: ["lib/aes-key.c:224", "lib/aes-key.c:225", "lib/aes-key.c:40"]
# Registers to ignore durin def-use analysis
dont_follow: ["K0", "K1", "K2", "K3", "K4", "K5", "K6", "K7"]
# Consider also register that hold a memory address in the def-use analysis
follow_mem_uses: False
