///
/// File: Parse output logs generated by the DR backend.
///
// Copyright (C) Microsoft Corporation
// SPDX-License-Identifier: MIT

#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "types/debug_trace.hpp"
#include "types/trace.hpp"

// =================================================================================================
// Parsing helpers
// =================================================================================================

/// @brief Parse entries of type T from an input stream and dump them to the
/// provided output
/// @tparam T Type of traces that are expected to be in the input stream
/// @param in_stream Input stream containing traces in binary format
/// @param out_stream Where to print the parsed entries
template <typename T>
static void parse(std::istream &in_stream, std::ostream &out_stream) {
  T entry{};
  while (not in_stream.eof()) {
    in_stream.read((char *)&entry, sizeof(T));
    entry.dump(out_stream);
  }
}

/// @brief Read a file generated by the DR backend and, depending on the marker,
/// deseralize it with the appropriate parser.
static bool parse_from_file(const std::string &filename, std::ostream &where) {
  std::fstream file(filename, std::ios::in | std::ios::binary);

  // Read the header to understand what type of trace are we deserializing
  char marker = 'U';
  file.read(&marker, 1);

  // Deserialize according to the type
  switch (marker) {
  case trace_entry_t::marker:
    parse<trace_entry_t>(file, where);
    return true;
  case debug_trace_entry_t::marker:
    parse<debug_trace_entry_t>(file, where);
    return true;

  default:
    return false;
  }
}

// =================================================================================================
// Main
// =================================================================================================

int main(int argc, const char *argv[]) {
  if (argc != 2) {
    std::cerr << "ERROR! Usage: ./parse_trace <path_to_trace>\n";
    return 1;
  }

  // Parse args from commandline
  std::vector<std::string> args(argv, argv + argc);

  // Parse entries from the provided path
  bool success = parse_from_file(args[1], std::cout);

  if (not success) {
    std::cerr << "ERROR! Could not understand the trace type -- was the file "
                 "generated by "
                 "Revizor's DR backend?\n";
    return 1;
  }

  return 0;
}
