///
/// File: Trace entries generated by the tracer
///
// Copyright (C) Microsoft Corporation
// SPDX-License-Identifier: MIT

#pragma once

#include <cstdint>

#include "observables.hpp"

/// @brief Type of trace entries that can be observed
enum class trace_entry_type_t : uint8_t {
    ENTRY_EOT = 0, // end of trace
    ENTRY_PC = 1,
    ENTRY_READ = 2,
    ENTRY_WRITE = 3,
};

/// @brief An entry of an observed trace
struct trace_entry_t {
    pc_t addr;     // pc for instructions; address for memory accesses
    uint32_t size; // instruction size for instructions; memory access size for memory accesses
    trace_entry_type_t type; // see trace_entry_type_t

    /// @brief Declare a marker to identify traces of this type
    static constexpr char marker = 'T';
};
